baseurl = "https://github.com/epogrebnyak/kppk-on-hugo"
title = "Развитие экспорта"
canonifyurls = true
paginate = 3


theme = "strange-case"

[params]
	colorScheme = "scheme-darkbrown"
	dateformat = "20.01.2006"
	description = "Комплексная программа поддержки конкурентоспособности"
	sidebarDescription = "Комплексная программа поддержки конкурентоспособности"
	sidebarFreeText = "Предприятия получат возможность поддержки из федерального бюджета и возьмут на себя обязательства по увеличению экспорта своей продукции."
	piwikSiteID = ""
	piwikURL = ""

[[menu.main]]
	name = "КППК"
	post = "<span class='glyphicon glyphicon-fire'></span>"
	url = "https://github.com/epogrebnyak/kppk-on-hugo"

[[menu.main]]
	name = "Bootstrap"
	post = "<span class='glyphicon glyphicon-ok'></span>"
	url = "http://getbootstrap.com"